POST https://node-rest-api-s7k3.onrender.com/videos
Content-type: application/json
  
{
    "title": "Maskara",
    "description": "Comedy film",
    "duration": 105
}

###

GET https://node-rest-api-s7k3.onrender.com/videos
//GET https://node-rest-api-s7k3.onrender.com/videos?search=node   I can use search...
  

###

PUT https://node-rest-api-s7k3.onrender.com/videos/dd96cde2-9529-4215-a3b1-b0a30b9580f5
Content-type: application/json

{
    "title": "Titanic",
    "description": "Drama film",
    "duration": 130
}


###

DELETE https://node-rest-api-s7k3.onrender.com/videos/3360c15a-4e1d-486c-98f6-cdb23c5c53ed


